Django/templates_demo/demoApp/urls.py
from django.urls import re_path,include
from demoApp import views

#template tagging for relative url

app_name = 'demoApp'

urlpatterns=[re_path(r'^other/',views.other,name='other'),
    re_path(r'^relative/',views.relative,name='relative'),
]

Django/templates_demo/templates_demo/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from demoApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',views.base,name='base'),
    re_path(r'^index/',views.index,name='index'),
    re_path(r'^demo/',include('demoApp.urls')),
]

Django/templates_demo/demoApp/models.py
from django.db import models

# Create your models here.

Django/templates_demo/demoApp/views.py
from django.shortcuts import render

# Create your views here.

def base(request):
	my_dict = {'text':'hello! welcome to template filter tutorial','ques':'how you doing?'}
	return render(request,'demoApp/base.html',my_dict)

def index(request):
	return render(request,'demoApp/index.html')


def other(request):
	return render(request,'demoApp/other.html')


def relative(request):
	return render(request,'demoApp/relative_url_template.html')

Django/templates_demo/templates/demoApp/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Base Page</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
	<nav class='navbar navbar-expand-lg navbar-light bg-light'>
		<div class='container'>
			<ul class='navbar-nav'>
				<li><a class='navbar-brand' href="{% url 'index' %}">BRAND</a></li>
				<li><a class='nav-item nav-link' href="{% url 'admin:index' %}">Admin</a></li>
				<li><a class='nav-item nav-link' href="{% url 'demoApp:other' %}">Other</a></li>
			</ul>	
		</div>
	</nav>
	<div class='container'>
		
		{% block body_block%}
		<!-- Anything outside this block is inherited -->
		<h1>Welcome to the base page</h1>
		{{ text| cut:'tutorial'}}
		<br>{{ ques | cut:'??'}}
		{% endblock %}
		
	</div>
	
</body>
</html>

Django/templates_demo/templates/demoApp/index.html
<!DOCTYPE html>
{% extends "demoApp/base.html" %}
	{% block endblock %}
	<h1>WELCOME TO INDEX</h1>
	<h2>This is an example from template inheritance</h2>
	{% endblock %}
<!--
<html>
<head>
	<title>Index Page</title>
</head>
<body>
	<h1>You are at Index Page</h1>
</body>
</html>
-->

Django/templates_demo/templates/demoApp/other.html
<!DOCTYPE html>
{% extends 'demoApp/base.html' %}
	{% block body_block %}
	<h1>WELCOME TO OTHER!</h1>
	<h2>This is an example for template inheritance</h2>
	{% endblock %}
<!--
<html>
<head>
	<title>Other Page</title>
</head>
<body>
	<h1>WELCOME TO OTHER!</h1>
	<a href="{% url 'index' %}">INDEX</a>
</body>
</html>
-->

Django/templates_demo/templates/demoApp/relative_url_template.html
<!DOCTYPE html>
<html>
<head>
	<title>Relative URL Page</title>
</head>
<body>
	<h1>WELCOME TO RELATIVE URL PAGE</h1>
	<a href="{% url 'demoApp:other' %}">OTHER</a>
</body>
</html>