Django/userauthentication/authApp/urls.py
from django.urls import re_path,include
from authApp import views

#template tagging

app_name = 'authApp'

urlpatterns = [
		re_path(r'^index/',views.index,name='index'),
		re_path(r'^register/',views.register,name='register'),
		re_path(r'^login/',views.user_login,name='user_login'),
]

Django/userauthentication/userauthentication/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from authApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',views.base,name='base'),
    re_path(r'^auth/',include('authApp.urls')),
    path('logout/', views.user_logout, name='logout'),
]

Django/userauthentication/authApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

	user = models.OneToOneField(User,on_delete=models.DO_NOTHING)

	portfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pic',blank=True)

	def __str__(self):
		return self.user.username

Django/userauthentication/authApp/forms.py
from django import forms
from django.contrib.auth.models import User
from authApp.models import UserProfileInfo


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model  = User
		fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo
		fields = ('portfolio_site','profile_pic')

Django/userauthentication/authApp/views.py
from django.shortcuts import render
from authApp.forms import UserForm,UserProfileInfoForm

# Create your views here.
def base(request):
	return render(request,'base.html')


def index(request):
	return render(request,'index.html')


def register(request):

	registered = False

	if request.method == 'POST':
		user_form = UserForm(request.POST)
		profile_form = UserProfileInfoForm(request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			
			user = user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit=False)
			profile.user = user

			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']

			profile.save()

			registered = True
		else:
			print(user_form.error,profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForm()

	return render(request,'registration.html',
		{'user_form':user_form,
		'profile_form':profile_form,
		'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('base'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'login.html', {})

def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('base'))

Django/userauthentication/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Base Page</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<nav class='navbar navbar-expand-lg navbar-light bg-light'>
	<div class = 'container'>
		<ul class="navbar-nav">
			<li><a class='navbar-brand' href="{% url 'base' %}">Django</a></li>
			<li><a class='nav-item nav-link' href="{% url 'admin:index' %}">Admin</a></li>
			<li><a class='nav-item nav-link' href="{% url 'authApp:register' %}">Registration</a></li>
		{# Some logic on what to display for last item#}
        	{% if user.is_authenticated %}
          		<a class="nav-link" href="{% url 'logout' %}">Logout</a>
        	{% else %}
         	 	<a class="nav-link" href="{% url 'authApp:user_login' %}">Login</a>
        	{% endif %}
		</ul>
	</div>
</nav>
<div class='container'>
	{% block body_block %}
	<h1>Hi there!, Welcome to the Base Page</h1>
	{% endblock%}
	
</div>
</body>
</html>

Django/userauthentication/templates/index.html
<!DOCTYPE html>
{% extends 'authApp/base.html' %}
{% block body_block %}

<div class='jumbotron'>
<h1>This is the index page</h1>	
</div>

{% endblock %}

Django/userauthentication/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'authApp:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

Django/userauthentication/templates/registration.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}

<div class='jumbotron'>
{% if registered %}
<h1>Thank you for registering!</h1>

{% else %}
<h1>Register Here!</h1>
<h3>Fill out the form</h3>

<form method='POST'>
	{% csrf_token %}
	{{ user_form.as_p }}
	{{ profile_form.as_p }}
	<input type="submit" name="" value='Register'>
</form>

{% endif %}


</div>
{% endblock %}